{
  "errorName": "UserAlreadyExistsException",
  "cause": "null",
  "errorMsg": "User with this email already exists!"
}